In [1]:
import numpy as np

In [2]:
my_lst=[1,2,3,4,5]

arr=np.array(my_lst)

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.shape

(5,)

In [5]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[3,4,5,6,7]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [6]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [7]:
arr.shape

(3, 5)

In [8]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [9]:
arr.reshape(3,5)

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [15]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [18]:
arr[1:4,2:4]

array([[4, 5],
       [5, 6]])

In [24]:
arr=np.arange(0,9,step=3)

In [25]:
arr

array([0, 3, 6])

In [26]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [27]:
 arr=np.arange(0,9)

In [28]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])